import type { Config } from "tailwindcss";

export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#d3e4fe",
        background: "#faf8ff",
        surface: "#faf8ff",
        "surface-bright": "#faf8ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f3ff",
        "surface-container": "#ecedfa",
        "surface-container-high": "#e6e7f4",
        "surface-container-highest": "#e1e2ee",
        "surface-dim": "#d8d9e6",
        "surface-variant": "#e1e2ee",
        "on-surface": "#191b24",
        "on-surface-variant": "#424656",
        "on-background": "#191b24",
        primary: "#0050cb",
        "primary-container": "#0066ff",
        "primary-fixed": "#dae1ff",
        "primary-fixed-dim": "#b3c5ff",
        "surface-tint": "#0054d6",
        "on-primary": "#ffffff",
        "on-primary-container": "#f8f7ff",
        "on-primary-fixed": "#001849",
        "on-primary-fixed-variant": "#003fa4",
        secondary: "#505f76",
        "secondary-container": "#d0e1fb",
        "secondary-fixed-dim": "#b7c8e1",
        "on-secondary-container": "#54647a",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#0b1c30",
        "on-secondary-fixed-variant": "#38485d",
        tertiary: "#a33200",
        "tertiary-container": "#cc4204",
        "tertiary-fixed": "#ffdbd0",
        "tertiary-fixed-dim": "#ffb59d",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#fff6f4",
        "on-tertiary-fixed": "#390c00",
        "on-tertiary-fixed-variant": "#832600",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        outline: "#727687",
        "outline-variant": "#c2c6d8",
        "inverse-primary": "#b3c5ff",
        "inverse-surface": "#2e303a",
        "inverse-on-surface": "#eff0fd",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        margin: "24px",
        xs: "4px",
        sm: "8px",
        md: "16px",
        gutter: "20px",
        lg: "24px",
        xl: "32px",
      },
      fontSize: {
        h1: ["30px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "600" }],
        h2: ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        h3: ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "mono-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
      },
      fontFamily: {
        sans: ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        mono: ["ui-monospace", "SFMono-Regular", "Menlo", "monospace"],
      },
      boxShadow: {
        panel: "0 2px 8px rgba(25, 27, 36, 0.06)",
        lift: "0 18px 50px rgba(0, 80, 203, 0.12)",
      },
    },
  },
  plugins: [],
} satisfies Config;
