[build]
target-dir = "target"

[target.m68k-unknown-none-elf]
linker = "m68k-elf-ld"
rustflags = [
    "-C", "link-arg=-Tapplets/alpha_usb/memory.x",
    "-C", "link-arg=--gc-sections",
    "-C", "relocation-model=pic",
    "-C", "panic=abort",
]
